version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  publisher:
    build: ./publisher
    depends_on:
      - redis
  subscriber:
    build: ./subscriber
    depends_on:
      - redis
